#pragma config(Motor,  motorA,          Ring,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheel1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheel2,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int spd = 80;
	int speed = 0;
	nxtDisplayCenteredTextLine(3, "Wheel Speeder!!!");
	wait1Msec(1000);
	nxtDisplayCenteredBigTextLine(1, "Adjust");
	nxtDisplayCenteredBigTextLine(4, "Speed");
	wait1Msec(1000);
	nxtDisplayCenteredBigTextLine(4, " ");
	nxtDisplayCenteredBigTextLine(1, " ");
	while(true){
		if(spd < 100){
			nxtDisplayCenteredTextLine(3, "%d", spd);
			nxtDisplayCenteredTextLine(4, " ");
		}
		if(spd == 100){
			nxtDisplayCenteredTextLine(3, "100");
			nxtDisplayCenteredTextLine(4, " ");
		}
		if(spd > 100){
			nxtDisplayCenteredTextLine(3, "100!!! I am ");
			nxtDisplayCenteredTextLine(4, "doing my best!");
			if(spd == 110){
				spd = 105;
			}
		}
		if(nNxtButtonPressed == 1){
			spd += 5;
			wait1Msec(350);

		}
		if(nNxtButtonPressed == 2){
			spd -= 5;
			wait1Msec(350);
		}
		if(nNxtButtonPressed == 3){
			speed = spd;
		}
		motor[wheel1] = speed;
		motor[wheel2] = speed;
	}
}
