#pragma config(Sensor, S1,     button,         sensorTouch)
#pragma config(Sensor, S2,     color,          sensorColorNxtFULL)
#pragma config(Motor,  motorA,          one,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Sorter,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Ring,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


bool manual = false;
bool mode1 = true;
bool mode2 = false;
bool up = false;
bool down = false;
int purple = 0;
int green = 0;
bool change = false;
bool reverse = false;
task ringOfFire(){
	while(true){
		if(manual == true){
			for(int i = 0; i < 45; i++){
				motor[Ring] = 7;
				wait1Msec(30);
			}
			for(int i = 0; i < 45; i++){
				motor[Ring] = -7;
				wait1Msec(30);
			}
			motor[Ring] = 0;
		}
	}
}

task control(){
	wait1Msec(17000);
	while(true){
		if(manual == false){
			nxtDisplayCenteredTextLine(5, "Automatic mode");
			wait1Msec(10);
		}
		else{
			nxtDisplayCenteredTextLine(5, "Manual Mode");
			wait1Msec(10);
		}
		if(nNxtButtonPressed == 1 && manual == true){
			manual = false;
			change = true;
			nxtDisplayCenteredBigTextLine(2, "Auto");
			nxtDisplayCenteredBigTextLine(4, "Mode");
			wait1Msec(1000);
			change = false;
			nxtDisplayCenteredBigTextLine(2, "    ");
			nxtDisplayCenteredBigTextLine(4, "    ");
		}
		if(manual == false){
			for(int i = 0; i < 45; i++){
				motor[one] = 7;
				wait1Msec(30);
				if(nNxtButtonPressed == 1 && manual == false){
					manual = true;
					change = true;
					nxtDisplayCenteredBigTextLine(2, "Manual");
					nxtDisplayCenteredBigTextLine(4, "Mode");
					wait1Msec(1000);
					change = false;
					nxtDisplayCenteredBigTextLine(2, "    ");
					nxtDisplayCenteredBigTextLine(4, "    ");
					break;
				}
			}
			for(int i = 0; i < 45; i++){
				motor[one] = -7;
				wait1Msec(30);
			}
			motor[one] = 0;
		}
		if(manual == true){
			if(SensorValue[button] == 1){
				for(int i = 0; i < 45; i++){
					motor[one] = 7;
					wait1Msec(30);
				}
				for(int i = 0; i < 45; i++){
					motor[one] = -7;
					wait1Msec(30);
				}
				motor[one] = 0;
			}
		}
	}
}

task main()
{
	startTask(ringOfFire);
	startTask(control);
	nxtDisplayCenteredBigTextLine(3, "Grape");
	wait1Msec(1000);
	nxtDisplayCenteredBigTextLine(3, "Sorter");
	wait1Msec(1000);
	nxtDisplayCenteredTextLine(2, "Default: green");
	nxtDisplayCenteredTextLine(3, "grapes up,");
	nxtDisplayCenteredTextLine(4, "purple grapes");
	nxtDisplayCenteredTextLine(5, "down.");
	wait1Msec(3000);
	nxtDisplayCenteredTextLine(2, "              ");
	nxtDisplayCenteredTextLine(5, "     ");
	for(int i = 0; i < 300; i++){
		nxtDisplayCenteredTextLine(3, "please put the");
		nxtDisplayCenteredTextLine(4, "purple grape");
		purple = SensorValue[color];
		wait1Msec(20);
	}
	for(int i = 0; i < 300; i++){
		nxtDisplayCenteredTextLine(3, "please put the");
		nxtDisplayCenteredTextLine(4, "green grape");
		green = SensorValue[color];
		wait1Msec(20);
	}
	while(true){
		bFloatDuringInactiveMotorPWM = false;
		if(mode1 == true && change == false){
			nxtDisplayCenteredTextLine(2, "green grapes up,");
			nxtDisplayCenteredTextLine(3, "purple grapes");
			nxtDisplayCenteredTextLine(4, "down.");
			wait1Msec(10);
		}
		if(mode2 == true && change == false){
			nxtDisplayCenteredTextLine(2, "purple grapes up,");
			nxtDisplayCenteredTextLine(3, "green grapes");
			nxtDisplayCenteredTextLine(4, "down.");
			wait1Msec(10);
		}
		if(nNxtButtonPressed == 3 && mode2 == false){
			mode2 = true;
			mode1 = false;
			reverse = true;
			nxtDisplayCenteredTextLine(2, "              ");
			nxtDisplayCenteredBigTextLine(3, "Reversed");
			nxtDisplayCenteredTextLine(5, "                 ");
			wait1Msec(1000);
			reverse = false;
		}

		if(nNxtButtonPressed == 3 && mode1 == false){
			mode1 = true;
			mode2 = false;
			reverse = true;
			nxtDisplayCenteredTextLine(2, "              ");
			nxtDisplayCenteredBigTextLine(3, "Default");
			nxtDisplayCenteredTextLine(5, "                 ");
			wait1Msec(1000);
			reverse = false;
		}
		if(mode1 == true && up == false && SensorValue[color] == green){
			for(int i = 0; i < 15; i++){
				motor[Sorter] = 75;
				wait1Msec(5);
			}
			motor[Sorter] = 0;
			up = true;
			down = false;
		}
		if(mode1 == true && down == false && SensorValue[color] == purple){
			for(int i = 0; i < 14; i++){
				motor[Sorter] = -75;
				wait1Msec(5);
			}
			motor[Sorter] = 0;
			down = true;
			up = false;
		}
		if(mode2 == true && down == false && SensorValue[color] == green){
			for(int i = 0; i < 14; i++){
				motor[Sorter] = -75;
				wait1Msec(5);
			}
			motor[Sorter] = 0;
			down = true;
			up = false;
		}
		if(mode2 == true && up == false && SensorValue[color] == purple){
			for(int i = 0; i < 15; i++){
				motor[Sorter] = 75;
				wait1Msec(5);
			}
			motor[Sorter] = 0;
			up = true;
			down = false;
		}
	}
}
